encryptor/encryptor/urls.py
from django.contrib import admin
from django.urls import path, include
from ui import views
from util import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ui.urls')),
    path('util/', include('util.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

encryptor/ui/urls.py
from django.urls import path
from . import views

app_name = 'ui'

urlpatterns = [
    path('', views.index, name='index'),
    path('encrypt/', views.encrypt_ui, name='encrypt'),
    path('decrypt/', views.decrypt_ui, name='decrypt'),
    path('success/', views.success, name='success'),
]

encryptor/util/urls.py
from django.urls import path
from . import views

app_name = "util"

urlpatterns = [
    path('generate_keys/', views.generate_keys, name='generate_keys'),
    path('encrypt/', views.encrypt, name='encrypt'),
    path('download/', views.download_file, name='download_file'),
    path('decrypt/', views.decrypt, name='decrypt'),
]

encryptor/ui/models.py
from django.db import models

# Create your models here.

encryptor/ui/forms.py
from django import forms

class FileEncryptForm(forms.Form):
    file = forms.FileField(label='File to encrypt')
    publicKey = forms.FileField(label='Receiver\'s Public Key')

class FileDecryptForm(forms.Form):
    file = forms.FileField(label='File to decrypt')
    privateKey = forms.FileField(label='Your Private Key')

encryptor/ui/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import FileEncryptForm, FileDecryptForm


# Create your views here.
def index(request):
    return render(request, 'ui/index.html')

def encrypt_ui(request):
    form = FileEncryptForm()
    return render(request, 'ui/encrypt.html', {'form': form})

def success(request):
    encrypted_file_path = request.session.get('encrypted_file_path')
    decrypted_file_path = request.session.get('decrypted_file_path')
    context = {'encrypted_file_path': encrypted_file_path,
               'decrypted_file_path': decrypted_file_path}
    return render(request, 'ui/success.html', context)

def decrypt_ui(request):
    form = FileDecryptForm()
    return render(request, 'ui/decrypt.html', {'form': form})

encryptor/ui/templates/ui/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'ui:index' %}">File Encryptor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ui:encrypt' %}">Encrypt File <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ui:decrypt' %}">Decrypt File</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'util:generate_keys' %}">Generate Keys</a>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

encryptor/ui/templates/ui/decrypt.html
<!-- file_encryptor.html -->

{% extends 'ui/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decrypt File</title>
</head>
<body>
    {% block content %}
<title>Decrypt File</title>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Decrypt File</h2>
                    <form method="POST" action="{% url 'util:decrypt' %}" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Decrypt</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

encryptor/ui/templates/ui/encrypt.html
{% extends 'ui/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encrypt File</title>
</head>
<body>
    {% block content %}
    <title>Encrypt File</title>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Encrypt File</h2>
                    <form method="POST" action="{% url 'util:encrypt' %}" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-block">Encrypt</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

encryptor/ui/templates/ui/index.html
<!-- ui/templates/index.html -->

{% extends 'ui/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Encryptor</title>
</head>
<body>
    {% block content %}
    <title>File Encryptor</title>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">File Encryptor</h2>
                    <p class="text-center">Enhance the security of your files through encryption. Begin by generating your encryption keys.</p>
                    <div class="mb-3">
                        <h5 class="text-center">Encrypt a File</h5>
                        <p class="text-center">To encrypt a file, upload the receiver's public key along with the file. The file can only be decrypted by the intended recipient using their private key.</p>
                    </div>
                    <div class="mb-3">
                        <h5 class="text-center">Decrypt a File</h5>
                        <p class="text-center">To decrypt a received file, upload your private key that corresponds to the public key shared with the sender.</p>
                    </div>
                    <div class="alert alert-warning text-center" role="alert">
                        <strong>Important:</strong> It is the sole responsibility of the user to secure their encryption keys. Users' keys are not stored anywhere on the server.
                    </div>
                    <a href="{% url 'ui:encrypt' %}" class="btn btn-primary btn-block">Encrypt File</a>
                    <a href="{% url 'ui:decrypt' %}" class="btn btn-primary btn-block">Decrypt File</a>
                    <a href="{% url 'util:generate_keys' %}" class="btn btn-primary btn-block">Generate Keys</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

encryptor/ui/templates/ui/success.html
<!-- ui/templates/success.html -->

{% extends 'ui/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if encrypted_file_path %}
            <div class="alert alert-success" role="alert">
                Files uploaded and encrypted successfully!
            </div>
            <a href="{% url 'util:download_file' %}?file={{ encrypted_file_path }}" class="btn btn-primary">Download Encrypted File</a>
            {% endif %}

            {% if decrypted_file_path %}
            <div class="alert alert-success" role="alert">
                Files decrypted successfully!
            </div>
            <a href="{% url 'util:download_file' %}?file={{ decrypted_file_path }}" class="btn btn-primary">Download Decrypted File</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}